# Exported from Render on 2025-07-20T04:04:50Z
services:
- type: web
  name: deeplink
  runtime: python
  repo: https://github.com/pich8989/deeplink
  branch: master
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn your_application.wsgi
  autoDeployTrigger: commit
version: "1"
